# Day 2: Colab 2C - Five Claims About a Dataset You've Never Seen

Names: Oliver Witt, Sarah Busby

Date: 09/01/2026

In [1]:
import pandas as pd

In [2]:
url = 'https://eds-217-essential-python.github.io/data/national_parks.csv'

In [3]:
nps_data = pd.read_csv(url)
nps_data.head()

,year,gnis_id,geometry,metadata,number_of_records,parkname,region,state,unit_code,unit_name,unit_type,visitors
0,1904,1163670,POLYGON,NaN,1,Crater Lake,PW,OR,CRLA,Crater Lake National Park,National Park,1500.0
1,1941,1531834,MULTIPOLYGON,NaN,1,Lake Roosevelt,PW,WA,LARO,Lake Roosevelt National Recreation Area,National Recreation Area,0.0
2,1961,2055170,MULTIPOLYGON,NaN,1,Lewis and Clark,PW,WA,LEWI,Lewis and Clark National Historical Park,National Historical Park,69000.0
3,1935,1530459,MULTIPOLYGON,NaN,1,Olympic,PW,WA,OLYM,Olympic National Park,National Park,2200.0
4,1982,277263,POLYGON,NaN,1,Santa Monica Mountains,PW,CA,SAMO,Santa Monica Mountains National Recreation Area,National Recreation Area,468144.0

In [4]:
nps_data.shape

(21560, 12)

In [5]:
nps_data.columns

Index(['year', 'gnis_id', 'geometry', 'metadata', 'number_of_records',
       'parkname', 'region', 'state', 'unit_code', 'unit_name', 'unit_type',
       'visitors'],
      dtype='object')

In [6]:
nps_data.dtypes

year                  object
gnis_id               object
geometry              object
metadata              object
number_of_records      int64
parkname              object
region                object
state                 object
unit_code             object
unit_name             object
unit_type             object
visitors             float64
dtype: object

In [7]:
nps_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21560 entries, 0 to 21559
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   year               21560 non-null  object
 1   gnis_id            21560 non-null  object
 2   geometry           21560 non-null  object
 3   metadata           18848 non-null  object
 4   number_of_records  21560 non-null  int64
 5   parkname           19342 non-null  object
 6   region             21560 non-null  object
 7   state              21560 non-null  object
 8   unit_code          21560 non-null  object
 9   unit_name          21560 non-null  object
 10  unit_type          21560 non-null  object
 11  visitors           21556 non-null  float64
dtypes: float64(1), int64(1), object(10)
memory usage: 2.0+ MB

In [8]:
nps_data['parkname'].value_counts()

parkname
Denali              192
Great Sand Dunes    170
Katmai              126
Glacier Bay         124
Yellowstone         114
                   ...
Keweenaw              2
Honouliuli            1
Pullman               1
Valles Caldera        1
Minidoka              1
Name: count, Length: 336, dtype: int64

In [9]:
nps_data['region'].value_counts()

region
IM    5765
NE    3710
SE    3503
PW    3251
MW    2635
NC    1579
AK    1040
NT      77
Name: count, dtype: int64

In [10]:
nps_data['unit_name'].value_counts()

unit_name
Yellowstone National Park            114
Crater Lake National Park            114
Kings Canyon National Park           114
Wind Cave National Park              114
Mount Rainier National Park          114
                                    ...
Keweenaw National Historical Park      2
Valles Caldera National Preserve       1
Honouliuli National Monument           1
Minidoka National Historic Site        1
Pullman National Monument              1
Name: count, Length: 386, dtype: int64

In [11]:
nps_data['unit_type'].value_counts()

unit_type
National Monument                        5051
National Park                            4743
National Historic Site                   3274
National Historical Park                 1984
National Memorial                        1486
National Battlefield                      859
National Recreation Area                  806
National Military Park                    613
National Preserve                         559
National Seashore                         494
Other Designation                         290
National Battlefield Park                 246
National Lakeshore                        177
Park                                      152
Parkway                                   149
National Parkway                           98
National Scenic Riverway                   93
National Historical Park and Preserve      81
National River                             79
Wild and Scenic River                      64
National Battlefield Site                  43
National Scenic River                      39
Scenic and Recreational River              38
National River and Recreation Area         37
War in the Pacific                         33
Ecological and Historic Preserve           26
National Reserve                           26
National Recreation River                  14
International Historic Site                 5
Valles Caldera National Preserve            1
Name: count, dtype: int64

In [12]:
nps_data.describe()

       number_of_records      visitors
count            21560.0  2.155600e+04
mean                 1.0  1.277105e+06
std                  0.0  1.190148e+07
min                  1.0  0.000000e+00
25%                  1.0  3.912475e+04
50%                  1.0  1.552190e+05
75%                  1.0  6.081438e+05
max                  1.0  8.719228e+08

### Claim 1:
Using the data learned from .describe(), we found that the dataset includes values for both yearly visitors and total vistors (i.e. everyone who has ever visited the park) in the same "visitors" column.  Therefore, any summary statistics from this column are useless.  For example, the minimum of this column is 0 (yearly vistors for years in which those parks didn't exist yet) and the maximum is 871 million (which is the total number of people who have ever visited Blue Ridge Parkway).

In [ ]:
keep = ['year' 'visitors' '' '' '']