# Day 3: Session 3B - The Filter Pattern

[Session Webpage](https://eds-217-essential-python.github.io/course-materials/interactive-sessions/3b_filtering_data.html)

Date: 09/02/2026

In [1]:
import pandas as pd

url = 'https://eds-217-essential-python.github.io/data/openaq_goleta_measurments.csv'
goleta = pd.read_csv(url)
goleta.shape

(1962, 15)

In [5]:
goleta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1962 entries, 0 to 1961
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    1962 non-null   int64
 1   location_name  1962 non-null   object
 2   parameter      1962 non-null   object
 3   value          1962 non-null   float64
 4   unit           1962 non-null   object
 5   datetimeUtc    1962 non-null   object
 6   datetimeLocal  1962 non-null   object
 7   timezone       1962 non-null   object
 8   latitude       1962 non-null   float64
 9   longitude      1962 non-null   float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     1962 non-null   object
 14  provider       1962 non-null   object
dtypes: float64(6), int64(1), object(8)
memory usage: 230.1+ KB

In [6]:
goleta['value'] > 20

0       False
1       False
2       False
3       False
4       False
        ...
1957    False
1958    False
1959    False
1960    False
1961    False
Name: value, Length: 1962, dtype: bool

In [11]:
keep = goleta['value'] > 20
print(f"keep is a {type(keep)} ")
gt_20 = goleta[keep]
gt_20.describe()

keep is a <class 'pandas.core.series.Series'>

,location_id,value,latitude,longitude,country_iso,isMobile,isMonitor
count,115.0,115.000000,1.150000e+02,1.150000e+02,0.0,0.0,0.0
mean,1186.0,25.373913,3.444530e+01,-1.198278e+02,NaN,NaN,NaN
std,0.0,4.288829,7.136523e-15,2.854609e-14,NaN,NaN,NaN
min,1186.0,21.000000,3.444530e+01,-1.198278e+02,NaN,NaN,NaN
25%,1186.0,22.000000,3.444530e+01,-1.198278e+02,NaN,NaN,NaN
50%,1186.0,24.000000,3.444530e+01,-1.198278e+02,NaN,NaN,NaN
75%,1186.0,27.000000,3.444530e+01,-1.198278e+02,NaN,NaN,NaN
max,1186.0,40.000000,3.444530e+01,-1.198278e+02,NaN,NaN,NaN

In [ ]:
gt_20b = goleta[goleta['value'] > 20]

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
720,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True
746,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True
795,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True
796,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True
797,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1226,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True
1227,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True
1376,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True
1712,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True
1873,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True

In [15]:
### The filter pattern

# df[df['column'] <comparison> value]

In [16]:
high_readings = goleta[goleta['value'] > 20]
high_readings.shape

(115, 15)

In [17]:
print('before:', goleta.shape)
print('after: ', high_readings.shape)

before: (1962, 15)
after:  (115, 15)

### filtering on text

In [21]:
ozone = goleta[goleta['parameter'] == 'o3']
ozone.head()

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,1186,Goleta,o3,0.025,ppm,2024-07-12T01:00:00+00:00,2024-07-11T18:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1,1186,Goleta,o3,0.028,ppm,2024-07-12T02:00:00+00:00,2024-07-11T19:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2,1186,Goleta,o3,0.029,ppm,2024-07-12T03:00:00+00:00,2024-07-11T20:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
3,1186,Goleta,o3,0.027,ppm,2024-07-12T04:00:00+00:00,2024-07-11T21:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
4,1186,Goleta,o3,0.026,ppm,2024-07-12T05:00:00+00:00,2024-07-11T22:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow

In [22]:
ozone.shape

(711, 15)

### practice

In [25]:
pm25 = goleta[goleta['parameter'] == 'pm25']

In [27]:
pm25.shape

(734, 15)

In [28]:
goleta['parameter'].value_counts()

parameter
pm25    734
o3      711
pm10    517
Name: count, dtype: int64

### two conditions at once

In [36]:
valid = (goleta['parameter'] == 'pm25') & (goleta['value'] > 9)
goleta[valid].describe()

,location_id,value,latitude,longitude,country_iso,isMobile,isMonitor
count,128.0,128.000000,1.280000e+02,1.280000e+02,0.0,0.0,0.0
mean,1186.0,12.304688,3.444530e+01,-1.198278e+02,NaN,NaN,NaN
std,0.0,2.678461,1.426669e-14,2.853339e-14,NaN,NaN,NaN
min,1186.0,10.000000,3.444530e+01,-1.198278e+02,NaN,NaN,NaN
25%,1186.0,10.000000,3.444530e+01,-1.198278e+02,NaN,NaN,NaN
50%,1186.0,11.000000,3.444530e+01,-1.198278e+02,NaN,NaN,NaN
75%,1186.0,14.000000,3.444530e+01,-1.198278e+02,NaN,NaN,NaN
max,1186.0,22.000000,3.444530e+01,-1.198278e+02,NaN,NaN,NaN

### Turning a condition around with ~
this is used for negation in pandas

In [39]:
not_pm25 = ~(goleta['parameter'] == 'pm25')
goleta[not_pm25].describe()

,location_id,value,latitude,longitude,country_iso,isMobile,isMonitor
count,1228.0,1228.000000,1.228000e+03,1.228000e+03,0.0,0.0,0.0
mean,1186.0,6.316756,3.444530e+01,-1.198278e+02,NaN,NaN,NaN
std,0.0,8.804334,7.108322e-15,1.421664e-14,NaN,NaN,NaN
min,1186.0,-1.000000,3.444530e+01,-1.198278e+02,NaN,NaN,NaN
25%,1186.0,0.021000,3.444530e+01,-1.198278e+02,NaN,NaN,NaN
50%,1186.0,0.032000,3.444530e+01,-1.198278e+02,NaN,NaN,NaN
75%,1186.0,13.000000,3.444530e+01,-1.198278e+02,NaN,NaN,NaN
max,1186.0,40.000000,3.444530e+01,-1.198278e+02,NaN,NaN,NaN

### Matching a list of values with .isin()

In [40]:
particulates = goleta[goleta['parameter'].isin(['pm25', 'pm10'])]
particulates.shape

(1251, 15)

In [41]:
of_interest = ['pm25', 'pm10']
goleta[goleta['parameter'].isin(of_interest)].shape

(1251, 15)